baseURL = 'https://reshidov.duckdns.org'

languageCode = 'ru-RU'
defaultContentLanguage = "ru-RU"
title = 'Reshidov Blog'
[module]
	[[module.imports]]
		path = "github.com/hugo-sid/hugo-blog-awesome"
[[params.socialIcons]]
name = "github"
url = "https://github.com/ereshidov"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/newfaceof"

[Languages.ru-RU.params.author]
	avatar = "avatar.png"
	intro = ""
	name = "Edem Reshidov"
	description = "Иногда пишу, чаще не пишу"